### ISSUE TITLE
DLL name too generic

### ISSUE THREAD

**Issue by W1zzardTPU** [intel/drivers.gpu.control-library#12]
Isn't a filename of "ControlLib.dll" way too generic? Especially when put into system32

https://github.com/intel/drivers.gpu.control-library/blob/d5be4626ebed6156ec90a3365baa8f8c5b18d7d7/wrapper/cApiWrapper.cpp#L39

Lots of other files/DLLs in the driver are prefixed with "ig" or "igfx"

**Comment by kpsam2000Intel** [comment]
Given already existing baseline and usage of this wrapper and DLL, this will be a hard one to change.

**Comment by kpsam2000Intel** [comment]
We have multiple OEM/ISV's already using this library
