### ISSUE TITLE
igcl problem:Sample_OverclockAPP.cpp

### ISSUE THREAD

**Issue by qianrushi123** [intel/drivers.gpu.control-library#18]
I test Sample_OverclockAPP.cpp and I test fail:
   ctl_result_t status              = ctlOverclockGetProperties(hDAhandle, &OcProperties);  parameter status return CTL_RESULT_ERROR_NOT_INITIALIZED,,What is the cause of this error

**Comment by kpsam2000Intel** [comment]
Pl describe the graphics driver and system configuration you have. I assume you do have CTL_INIT_FLAG_USE_LEVEL_ZERO mentioned in flags member?

**Comment by ashutosh-d-shukla** [comment]
@qianrushi123 closing this old issue as there is no update for almost 6 months now.
