### ISSUE TITLE
CTL_RESULT_ERROR_PLATFORM_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Tellusim** [intel/drivers.gpu.control-library#19]
Hello,

We always have CTL_RESULT_ERROR_PLATFORM_NOT_SUPPORTED error in any sample.
Zero initialization flags and "run as administrator" do not help to initialize the library.

library handle 00007FF9389B0000
proc address 00007FF9389B4F40
Overrall test result is 0x40000020

NUC11PAHi5 + Arc A380 eGPU
Windows 10 with 31.0.101.3277 driver

Thank you

**Comment by Tellusim** [comment]
The library is not compatible with eGPU over Thunderbolt.
Everything is fine with the "internal" GPU over PCI express.

**Comment by IAmAnkur** [comment]
eGPU is not supported currently

**Comment by ashutosh-d-shukla** [comment]
Closing old issue, no plan to add support for eGPU as of now.
