### ISSUE TITLE
eployment environment  issue

### ISSUE THREAD

**Issue by lixinlei24** [intel/drivers.gpu.control-library#31]
Please, briefly describe the igcl  deployment environment.My laptop model is 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz   2.50 GHz.Run the project show the  " 0x40000020,   Platform not supported" or  " 0x40000009,  Generic error code for unsupported versions",so i want to know the igcl  deployment environment to run the sample! Thanks.

**Comment by IAmAnkur** [comment]
Please find information about platform support at https://intel.github.io/drivers.gpu.control-library/prog.html#system-requirements

**Comment by lixinlei24** [comment]
Received. Thank you very much for your reply






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "intel/drivers.gpu.control-library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [intel/drivers.gpu.control-library] eployment environment  issue (Issue #31)





 
Please find information about platform support at https://intel.github.io/drivers.gpu.control-library/prog.html#system-requirements

**Comment by murali-i** [comment]
Closing as issue is addressed.
