### ISSUE TITLE
ctlEnumerateDevices returns adapter count of zero for Intel UHD enable hardware

### ISSUE THREAD

**Issue by Twon** [intel/drivers.gpu.control-library#34]
Running the samples on a laptop with [Intel® UHD Graphics for 11th Gen Intel® Processors](https://ark.intel.com/content/www/us/en/ark/products/213803/intel-core-i711800h-processor-24m-cache-up-to-4-60-ghz.html) ctlEnumerateDevices turns an adapter count of zero. Can you confirm the library should see this, and if not why not?  Many thanks.

**Comment by rahulrgandhi99** [comment]
Control library is not supported on [Intel® UHD Graphics for 11th Gen Intel® Processors](https://ark.intel.com/content/www/us/en/ark/products/213803/intel-core-i711800h-processor-24m-cache-up-to-4-60-ghz.html) that is why it is reporting 0 adapters but we fixed this It will report unsupported platform instead of 0 adapters in latest drops.

**Comment by paulober** [comment]
But does it then return for `graphics_adapter_properties`:
```
enumerator CTL_ADAPTER_PROPERTIES_FLAG_INTEGRATED:
[out] Is Integrated Graphics adapter
```

**Comment by rahulrgandhi99** [comment]
for Arc dGPUs it won't set this flag **enumerator CTL_ADAPTER_PROPERTIES_FLAG_INTEGRATED:
[out] Is Integrated Graphics adapter** as it is not internal graphics adapter.

**Comment by Twon** [comment]
> Control library is not supported on [Intel® UHD Graphics for 11th Gen Intel® Processors](https://ark.intel.com/content/www/us/en/ark/products/213803/intel-core-i711800h-processor-24m-cache-up-to-4-60-ghz.html) that is why it is reporting 0 adapters but we fixed this It will report unsupported platform instead of 0 adapters in latest drops.

Thanks, that's a more helpful output and I see that on the latest version of the drivers.   

However, as a user, it was not clear to me on encountering this error as to if this should work or not. Is it documented anywhere which systems this library is supported on?  Also is there a road map documenting which systems are going to be supported in the future?  Without this information hard to assess the value of supporting this library.

**Comment by rahulrgandhi99** [comment]
Please find information about platform support at https://intel.github.io/drivers.gpu.control-library/prog.html#system-requirements

**Comment by ashutosh-d-shukla** [comment]
Closing this as the query is already addressed in the comments.
