### ISSUE TITLE
ctlInit returns CTL_RESULT_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by PeterTh** [intel/drivers.gpu.control-library#38]
When I try to use IGCL (with the included wrapper), I get a `CTL_RESULT_ERROR_NOT_INITIALIZED` return value from my call to `ctlInit`.
As far as I can tell, that should never happen (since that return value isn't listed as one of the possibilities for that function)

Stepping through the wrapper code, I could determine that finding the dll and looking up the `ctlInit` function in it is working fine.

**Comment by kpsam2000Intel** [comment]
Please share your graphics config. IGCL is not supported for certain older systems/Integrated graphics.

**Comment by ashutosh-d-shukla** [comment]
@PeterTh any updates on the complete configuration of your system?

**Comment by ashutosh-d-shukla** [comment]
Closing as inactive, please let us know if issue is still seen with the complete config details.
