### ISSUE TITLE
result data not found when ctlGetSet3DFeature for app

### ISSUE THREAD

**Issue by paulober** [intel/drivers.gpu.control-library#39]
I get a `CTL_RESULT_ERROR_DATA_NOT_FOUND` when trying to read settings for a game. I set appname to the name of the exe like in the sample. For example "GTA5.exe".  And i prviously added the game to Arc Control and changed the setting there before i read setting for this app. If i change the values by my self it returns success but if i then want to load them i get the same DATA NOT FOUND and sometime a value i've set serveral trys before.
Is there any way to get all the app specific settings which has been made?
And could i've done wrong?

**Comment by rahulrgandhi99** [comment]
can you please paste your set and get code here?

**Comment by paulober** [comment]
> can you please paste your set and get code here?

```cpp
if (h_api_handle_ == nullptr || *adapter_count_ < 1 || selected_device_ < 0)
{
    return false;
}

ctl_3d_feature_getset_t set_3d_property{ 0 };
set_3d_property.Size = sizeof(ctl_3d_feature_getset_t);

set_3d_property.FeatureType = CTL_3D_FEATURE_GAMING_FLIP_MODES;
set_3d_property.bSet = true;
set_3d_property.CustomValueSize = 0;
set_3d_property.pCustomValue = nullptr;

// application specify
if (application != nullptr)
{
    //app_name is of type: const char* app_name
    set_3d_property.ApplicationName = const_cast<char*>(app_name);
    set_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(app_name));
}

set_3d_property.ValueType = CTL_PROPERTY_VALUE_TYPE_ENUM;
set_3d_property.Value.EnumType.EnableType = static_cast<ctl_gaming_flip_mode_flag_t>(flip_mode);
set_3d_property.Version = 0;

if (h_devices_ != nullptr)
{
    WRITE_LINE("Trying to set CTL_3D_FEATURE_GAMING_FLIP_MODES to "
        + set_3d_property.Value.EnumType.EnableType);
    
    if (const ctl_result_t result = ctlGetSet3DFeature(h_devices_[selected_device_], &set_3d_property);
        result == CTL_RESULT_SUCCESS)
    {
        return true;
    }

    WRITE_LINE("Failed to set 3d feature of type CTL_3D_FEATURE_GAMING_FLIP_MODES.");
}

return false;
```

**Comment by rahulrgandhi99** [comment]
> 

This is only set code. seems correct. Please paste your get code as well as you are facing ICTL_RESULT_ERROR_DATA_NOT_FOUND when you are trying to read settings for a game.

**Comment by paulober** [comment]
Ok, here is the get code:
```c
if (h_api_handle_ == nullptr || *adapter_count_ < 1 || selected_device_ < 0)
{
    return CTL_GAMING_FLIP_MODE_FLAG_MAX;
}

ctl_3d_feature_getset_t get_3d_property{0};
get_3d_property.Size = sizeof(ctl_3d_feature_getset_t);

get_3d_property.FeatureType = CTL_3D_FEATURE_GAMING_FLIP_MODES;
get_3d_property.bSet = false;
get_3d_property.CustomValueSize = 0;
get_3d_property.pCustomValue = nullptr;
// application specify
if (application != nullptr)
{
    // app_name is of type: const char* app_name
    get_3d_property.ApplicationName = const_cast<char*>(app_name);
    get_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(app_name));
}
get_3d_property.ValueType = CTL_PROPERTY_VALUE_TYPE_ENUM;
get_3d_property.Version = 0;

if (h_devices_ != nullptr)
{
    if (const ctl_result_t result = ctlGetSet3DFeature(h_devices_[selected_device_], &get_3d_property);
        result == CTL_RESULT_SUCCESS)
    {
        const auto gfm = static_cast<ctl_gaming_flip_mode_flag_t>(get_3d_property.Value.EnumType.EnableType);
        return gfm;
    }
    else
    {
        WRITE_LINE("error reading global gaming flip mode! Result: "
            + decode_ret_code(result).c_str());
    }
}

return CTL_GAMING_FLIP_MODE_FLAG_MAX;
```

**Comment by rahulrgandhi99** [comment]
> Ok, here is the get code:
> 
> ```c
> if (h_api_handle_ == nullptr || *adapter_count_ < 1 || selected_device_ < 0)
> {
>     return CTL_GAMING_FLIP_MODE_FLAG_MAX;
> }
> 
> ctl_3d_feature_getset_t get_3d_property{0};
> get_3d_property.Size = sizeof(ctl_3d_feature_getset_t);
> 
> get_3d_property.FeatureType = CTL_3D_FEATURE_GAMING_FLIP_MODES;
> get_3d_property.bSet = false;
> get_3d_property.CustomValueSize = 0;
> get_3d_property.pCustomValue = nullptr;
> // application specify
> if (application != nullptr)
> {
>     // app_name is of type: const char* app_name
>     get_3d_property.ApplicationName = const_cast<char*>(app_name);
>     get_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(app_name));
> }
> get_3d_property.ValueType = CTL_PROPERTY_VALUE_TYPE_ENUM;
> get_3d_property.Version = 0;
> 
> if (h_devices_ != nullptr)
> {
>     if (const ctl_result_t result = ctlGetSet3DFeature(h_devices_[selected_device_], &get_3d_property);
>         result == CTL_RESULT_SUCCESS)
>     {
>         const auto gfm = static_cast<ctl_gaming_flip_mode_flag_t>(get_3d_property.Value.EnumType.EnableType);
>         return gfm;
>     }
>     else
>     {
>         WRITE_LINE("error reading global gaming flip mode! Result: "
>             + decode_ret_code(result).c_str());
>     }
> }
> 
> return CTL_GAMING_FLIP_MODE_FLAG_MAX;
> ```

Seems correct to me please verify below condition in your code
if (application != nullptr)
{
    // app_name is of type: const char* app_name
    get_3d_property.ApplicationName = const_cast<char*>(app_name);
    get_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(app_name));
}

is it restricting to populate application name in the structure?

please refer below Screen-shot 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/85487817/213969038-b8188253-5dd4-4e81-aa82-a452878b455f.png">

your structure should be populated as mentioned in above screen-shot

**Comment by paulober** [comment]
> Seems correct to me please verify below condition in your code if (application != nullptr) { // app_name is of type: const char* app_name get_3d_property.ApplicationName = const_cast<char*>(app_name); get_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(app_name)); }
> 
> is it restricting to populate application name in the structure?
> 
> please refer below Screen-shot
> 
> <img alt="image" width="407" src="https://user-images.githubusercontent.com/85487817/213969038-b8188253-5dd4-4e81-aa82-a452878b455f.png">
> 
> your structure should be populated as mentioned in above screen-shot

The condition seems strange because it originally looks like this:
```cpp
if (application != nullptr)
  {
      std::string app_name = marshal_as<std::string>(application);
      // +1 for the NULL terminator
      char* pBuf = new char[app_name.length() + 1];
      strcpy_s(pBuf, app_name.length() + 1, app_name.c_str());
      set_3d_property.ApplicationName = pBuf;
      set_3d_property.ApplicationNameLength = sizeof pBuf;
  }
```
`application` is of type `String^` thats why this conversion is happening but as you can see in the debuger its working:

![image](https://user-images.githubusercontent.com/44974737/214094523-1f725762-d7f7-433d-9f74-619c7d797aa7.png)

**Comment by paulober** [comment]
But I still get `-547470120` error code...

**Comment by paulober** [comment]
But when i set it I get SUCCESS for the set function call

**Comment by paulober** [comment]
Ok, so if i replace my `ApplicationNameLength` code with:
```cpp
get_3d_property.ApplicationNameLength = static_cast<int8_t>(strlen(pBuf));
```
it works.
