### ISSUE TITLE
ADL EdidMgmt failure: 0x40000017

### ISSUE THREAD

**Issue by hangfu-guo** [intel/drivers.gpu.control-library#47]
Hi,

I added a new registry key: EdidMgmtEnable(Dword, value = 1).
But the sample "EdidManagement" still output failure.

Tried rebuild the code, same failure result.

Is there any more BKM i can use to successfully run these samples?

**Comment by rahulrgandhi99** [comment]
Hi @hangfu-guo, EDID management is only supported with HDMI & DP interfaces. with which interface you are trying?

**Comment by hangfu-guo** [comment]
@rahulrgandhi99 Thanks for reply. Already found that EDID management currently doesn't support ADL-S.
