### ISSUE TITLE
Call ctlEnumTemperatureSensors return CTL_RESULT_ERROR_ZE_LOADER in Win32 app

### ISSUE THREAD

**Issue by bozax** [intel/drivers.gpu.control-library#53]
My win32 app call ctlEnumTemperatureSensors return CTL_RESULT_ERROR_ZE_LOADER ,but win64 app is ok. Is this func is not support win32 or video driver is not contain ze_loader.dll for win32 app?

**Comment by ezhilintc** [comment]
As in the NOTES section, Temperature APIs are only supported for 64b.

**Comment by ashutosh-d-shukla** [comment]
This is expected behavior and supported only for 64 bit as mentioned above, closing the issue.
