### ISSUE TITLE
ctlInit returns CTL_RESULT_ERROR_INVALID_NULL_HANDLE.

### ISSUE THREAD

**Issue by 2023BI** [intel/drivers.gpu.control-library#57]
I'm trying to access AUX using ControlLib.dll, but get a return value, CTL_RESULT_ERROR_INVALID_NULL_HANDLE, after calling ctlInit. Unfortunately, I could not find the ERROR code at IGCL API Documentation ( https://intel.github.io/drivers.gpu.control-library/Control/api.html#ctlinit ). 
Anyway, the sample code( I2C_AUX_Sample_App.cpp ) is used with no change. Could you help me solve this problem?

- Display : Intel(R) UHD Graphics ( Driver Version: 27.20.100.8329 )
- Processor : 11th Gen Intel(R) Core(TM) i7-1165G7 @2.80GHz
- ControlLib.dll ( https://software.intel.com/sites/downloads/symbols/ControlLib.dll/608BE3B458000/ )

**Comment by ashutosh-d-shukla** [comment]
11th Gen Intel(R) Core(TM) i7-1165G7 @2.80GHz is internally codenamed TGL and not a POR product for this project. Rejecting this issue.
