### ISSUE TITLE
can't get the correct color model

### ISSUE THREAD

**Issue by Petercg** [intel/drivers.gpu.control-library#60]
I'm trying to get the value of input range in  "Intel® Graphics Command Center", but whatever I set:FULL or Limited, what I get that with function: GetPixTxCapability is always 0.
Could you help me solve this problem?

Display :Intel(R) UHD Graphics 710（version:31.0.101.4688）
Processor : Intel(R) Pentium(R) Gold G7400 3.70GHz

**Comment by ashutosh-d-shukla** [comment]
@mani-kr to check and update the IGCL version where this is fixed, will share the driver version post that.

**Comment by ashutosh-d-shukla** [comment]
This is fixed in our internal version 15225, yet to be released as production driver on intel.com - ETA WW4.5'24

**Comment by ashutosh-d-shukla** [comment]
Drivers 31.0.101.5333 should have this support.
