### ISSUE TITLE
Missing sample config file in CombinedDisplay

### ISSUE THREAD

**Issue by michaelguo** [intel/drivers.gpu.control-library#69]
As title, please share the missing sample config file:

Config File - sample config file
Enable.cfg - Enabling 1x2 mode of Combined Display with 1080p displays
Disable.cfg - Disabling Combined Display
Query.cfg - Querying current Combined Display topology

**Comment by murali-i** [comment]
This is fixed here:
https://github.com/intel/drivers.gpu.control-library/commit/bfc8d4cc5786711e02eb4f779b1b2353c85774c9
