### ISSUE TITLE
ctlInit() doesn't work on IceLake

### ISSUE THREAD

**Issue by Valkirie** [intel/drivers.gpu.control-library#70]
I've been successfully working on [an external DLL library](https://github.com/Valkirie/drivers.gpu.control-library/blob/2fcb7100b32beb6f09a061990c56a2c8a3aa2926/Samples/Wrapper/Wrapper.cpp#L409) to be then called by my C# application to manage some aspects of IGCL.

I'm getting good results on my 11900KB and its A770 but I can't seams to get a handle on IceLake with embedded GPU.
Can you help ?

**Comment by ashutosh-d-shukla** [comment]
Control library is not supported on Icelake and is supported from Alderlake onwards.
