### ISSUE TITLE
odd repository structure

### ISSUE THREAD

**Issue by tycho** [intel/drivers.gpu.control-library#83]
Is this intended?

![image](https://github.com/intel/drivers.gpu.control-library/assets/29616/1bca8cde-a5fe-4311-8d0f-9be4c3f6d80c)

Which is considered current? Both source files differ across the two folders...

**Comment by rahulrgandhi99** [comment]
Please consider below files 
Source -> cApiWrapper.cpp
include-> igcl_api.h

**Comment by murali-i** [comment]
this is fixed now
