### ISSUE TITLE
C++ program to fetch the Intel Arc GPU and VRAM usage

### ISSUE THREAD

**Issue by vamshigowda56vg-git** [intel/drivers.gpu.control-library#95]
can anyone provide an example C++ program to fetch Intel Arc GPU and VRAM usage?

**Comment by ashutosh-d-shukla** [comment]
Please refer to https://github.com/intel/drivers.gpu.control-library/blob/master/Samples/Overclocking_Sample/Sample_OverclockAPP.cpp for reference. Resolving this. If specific queries are there feel free to reopen. Tagging @ezhilintc as FYI

**Comment by ezhilintc** [comment]
Refer below functions and the API usages in this sample application
https://github.com/intel/drivers.gpu.control-library/blob/master/Samples/Telemetry_Samples/Sample_TelemetryAPP.cpp
| function | API to get usage | 
|-|-|
| CtlMemoryTest | ctlMemoryGetState |
| CtlEngineTest | ctlEngineGetActivity |
