### ISSUE TITLE
alternative library for older gpu ?

### ISSUE THREAD

**Issue by Meldryt** [intel/drivers.gpu.control-library#96]
Does anyone know a similar intel  gpu telemetry library, which supports intel graphics older than Alderlake (12th gen)?

**Comment by ashutosh-d-shukla** [comment]
Alderlake should still be supported with the current library itself. Please let us know if you are facing issues, share the exact system config with version of drivers and the sample app you are running with the IGCL that fails. Feel free to reopen this issue with the config.
